Rtt\QueryBundle\Event:
    fields:
        id:
            id:  true
        name:
            type: string
        price:
            type: float


        type :
            type : string

        element_x :
            type : string

        client_x:
            type : string