api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard/

